// Espécies, comportamento e tabelas de materiais dos inimigos.
// O loot é definido pela espécie, não por uma tabela genérica do mapa.

export const ENEMY_SPECIES = Object.freeze({
    rat: Object.freeze({ id: "rat", type: "animal", nameKey: "enemies.species.rat", bossNameKey: "enemies.bosses.rat", baseStats: { hp: 18, damage: 4, defense: 1, speed: 3 }, behavior: "pack", materials: [{ id: "rat_fur", nameKey: "materials.ratFur", min: 1, max: 2, chance: 1 }, { id: "disease_gland", nameKey: "materials.diseaseGland", min: 1, max: 1, chance: 0.18 }] }),
    wolf: Object.freeze({ id: "wolf", type: "animal", nameKey: "enemies.species.wolf", bossNameKey: "enemies.bosses.wolf", baseStats: { hp: 32, damage: 8, defense: 2, speed: 4 }, behavior: "pack", materials: [{ id: "wolf_pelt", nameKey: "materials.wolfPelt", min: 1, max: 2, chance: 1 }, { id: "wolf_fang", nameKey: "materials.wolfFang", min: 1, max: 2, chance: 0.45 }, { id: "sinew", nameKey: "materials.sinew", min: 1, max: 2, chance: 0.3 }] }),
    boar: Object.freeze({ id: "boar", type: "animal", nameKey: "enemies.species.boar", bossNameKey: "enemies.bosses.boar", baseStats: { hp: 42, damage: 9, defense: 4, speed: 2 }, behavior: "charge", materials: [{ id: "boar_hide", nameKey: "materials.boarHide", min: 1, max: 2, chance: 1 }, { id: "boar_tusk", nameKey: "materials.boarTusk", min: 1, max: 2, chance: 0.55 }, { id: "raw_meat", nameKey: "materials.rawMeat", min: 1, max: 3, chance: 0.7 }] }),
    spider: Object.freeze({ id: "spider", type: "animal", nameKey: "enemies.species.spider", bossNameKey: "enemies.bosses.spider", baseStats: { hp: 24, damage: 7, defense: 2, speed: 3 }, behavior: "ambush", materials: [{ id: "spider_silk", nameKey: "materials.spiderSilk", min: 1, max: 3, chance: 1 }, { id: "venom_gland", nameKey: "materials.venomGland", min: 1, max: 1, chance: 0.35 }] }),
    slime: Object.freeze({ id: "slime", type: "slime", nameKey: "enemies.species.slime", bossNameKey: "enemies.bosses.slime", baseStats: { hp: 28, damage: 6, defense: 3, speed: 1 }, behavior: "corrode", materials: [{ id: "slime_core", nameKey: "materials.slimeCore", min: 1, max: 2, chance: 1 }, { id: "acid_gland", nameKey: "materials.acidGland", min: 1, max: 1, chance: 0.3 }] }),
    bandit: Object.freeze({ id: "bandit", type: "humanoid", nameKey: "enemies.species.bandit", bossNameKey: "enemies.bosses.bandit", baseStats: { hp: 38, damage: 10, defense: 3, speed: 2 }, behavior: "tactical", materials: [{ id: "scrap_metal", nameKey: "materials.scrapMetal", min: 1, max: 3, chance: 0.8 }, { id: "cloth_scrap", nameKey: "materials.clothScrap", min: 1, max: 2, chance: 0.65 }], itemCategories: ["weapon", "equipment"] }),
    harpy: Object.freeze({ id: "harpy", type: "beast", nameKey: "enemies.species.harpy", bossNameKey: "enemies.bosses.harpy", baseStats: { hp: 35, damage: 11, defense: 2, speed: 4 }, behavior: "flying", materials: [{ id: "feather", nameKey: "materials.feather", min: 1, max: 3, chance: 1 }, { id: "talon", nameKey: "materials.talon", min: 1, max: 2, chance: 0.5 }] }),
    golem: Object.freeze({ id: "golem", type: "construct", nameKey: "enemies.species.golem", bossNameKey: "enemies.bosses.golem", baseStats: { hp: 75, damage: 15, defense: 10, speed: 1 }, behavior: "guard", materials: [{ id: "stone_core", nameKey: "materials.stoneCore", min: 1, max: 2, chance: 1 }, { id: "iron_fragment", nameKey: "materials.ironFragment", min: 1, max: 3, chance: 0.75 }] }),
    dragonkin: Object.freeze({ id: "dragonkin", type: "beast", nameKey: "enemies.species.dragonkin", bossNameKey: "enemies.bosses.dragonkin", baseStats: { hp: 90, damage: 18, defense: 8, speed: 2 }, behavior: "elemental", materials: [{ id: "scale", nameKey: "materials.scale", min: 1, max: 3, chance: 1 }, { id: "dragon_blood", nameKey: "materials.dragonBlood", min: 1, max: 1, chance: 0.2 }] }),
    skeleton: Object.freeze({ id: "skeleton", type: "undead", nameKey: "enemies.species.skeleton", bossNameKey: "enemies.bosses.skeleton", baseStats: { hp: 30, damage: 9, defense: 4, speed: 2 }, behavior: "relentless", materials: [{ id: "bone", nameKey: "materials.bone", min: 1, max: 3, chance: 1 }, { id: "old_metal", nameKey: "materials.oldMetal", min: 1, max: 2, chance: 0.45 }], itemCategories: ["weapon"] }),
    cultist: Object.freeze({ id: "cultist", type: "humanoid", nameKey: "enemies.species.cultist", bossNameKey: "enemies.bosses.cultist", baseStats: { hp: 34, damage: 12, defense: 2, speed: 2 }, behavior: "ritual", materials: [{ id: "dark_cloth", nameKey: "materials.darkCloth", min: 1, max: 2, chance: 0.8 }, { id: "ritual_ink", nameKey: "materials.ritualInk", min: 1, max: 1, chance: 0.35 }], itemCategories: ["consumable", "weapon"] }),
    shade: Object.freeze({ id: "shade", type: "aberration", nameKey: "enemies.species.shade", bossNameKey: "enemies.bosses.shade", baseStats: { hp: 45, damage: 14, defense: 3, speed: 3 }, behavior: "phase", materials: [{ id: "ectoplasm", nameKey: "materials.ectoplasm", min: 1, max: 2, chance: 1 }, { id: "shadow_shard", nameKey: "materials.shadowShard", min: 1, max: 1, chance: 0.25 }] })
});

export const ENEMY_SPECIES_LIST = Object.freeze(Object.values(ENEMY_SPECIES));
