export const LANGUAGES = [{ code: "pt-BR", label: "Português (Brasil)" }, { code: "en", label: "English" }];
const P = {
 "pt-BR": {
  language: { title: "Selecione o idioma", description: "Escolha o idioma da interface.", hint: "Use as setas para escolher e Enter para confirmar.", selected: "Idioma selecionado." },
  main: { title: "Menu principal", continue: "Continuar jogo", newGame: "Novo jogo", options: "Opções", credits: "Créditos", noSave: "Nenhum jogo salvo disponível." },
  options: { title: "Opções", language: "Idioma", controls: "Controles", accessibility: "Acessibilidade", defaults: "Restaurar configurações padrão", languageInfo: "Selecione o idioma da interface.", controlsInfo: "Setas: mover. Shift mais setas: olhar.", accessibilityInfo: "Anúncios compatíveis com leitores de tela.", defaultsInfo: "Configurações restauradas." },
  credits: { title: "Créditos", description: "Zenit é desenvolvido pela equipe Euconcegojogar.", contact: "Contato: euconcego@gmail.com", back: "Pressione Escape para voltar." },
  startup: { newGame: "Novo jogo iniciado.", controls: "Use as setas para mover e C para abrir o menu." }, common: { choose: "Use as setas para escolher e Enter para confirmar.", back: "Pressione Escape para voltar." },
  gameplay: { map: "Mapa", level: "nível", mainMenu: "Menu principal", status: "Status", inventory: "Inventário", equipment: "Equipamento", class: "Classe", power: "Potência", coordination: "Coordenação", mind: "Mente", hp: "HP", stamina: "Estamina", mana: "Mana", gold: "Ouro", empty: "Vazio", box: "Caixa", range: "alcance", head: "Cabeça", neck: "Pescoço", ring1: "Anel 1", ring2: "Anel 2", torso: "Tronco", body: "Sobre o Corpo", waist: "Cintura", legs: "Pernas", feet: "Pés", melee: "Arma Corpo a Corpo", ranged: "Arma à Distância", shield: "Escudo", direction: { CIMA: "cima", BAIXO: "baixo", ESQUERDA: "esquerda", DIREITA: "direita" }, item: { "Vanguarda / Campeão": "Vanguarda / Campeão", "Caçador / Patrulheiro": "Caçador / Patrulheiro", "Místico / Erudito": "Místico / Erudito", "Espada Curta": "Espada Curta", "Arco Curto": "Arco Curto" }, messages: { boundary: "Fronteira do mapa alcançada.", doorAhead: " Porta à frente. Pressione Enter para abrir.", boxAhead: " A caixa deve ser destruída ou contornada.", blocked: "Caminho bloqueado para", scanWall: "parede em", scanBox: "caixa em", scanDoor: "porta em", scanNone: "nenhum obstáculo ou porta relevante no campo de visão", scanDone: "Varredura em cone concluída", noWeapon: "Nenhuma arma equipada nesta instância.", attackWall: "Ataque bloqueado por parede em", attackDoor: "A porta bloqueia o ataque. Pressione Enter para interagir com ela.", destroyed: "destruída. Você encontrou", total: "Total", attackDone: "Ataque desferido com", noTarget: "Nenhum alvo ao alcance.", nothing: "Nada com que interagir nesta direção.", doorOpened: "Porta aberta. Você avançou para o nível", activeWeapon: "Arma ativa", none: "nenhuma", looking: "Você está olhando para", look: "Olhar direcionado para", menuHint: "Use as setas, Enter para selecionar e Escape para fechar.", submenuStatus: "Submenu de Status.", submenuEquipment: "Submenu de Equipamento.", inventoryEmpty: "Inventário vazio.", option: "Opção" } }
 },
 en: {
  language: { title: "Select language", description: "Choose the interface language.", hint: "Use the arrow keys to choose and Enter to confirm.", selected: "Language selected." },
  main: { title: "Main menu", continue: "Continue game", newGame: "New game", options: "Options", credits: "Credits", noSave: "No saved game is available." },
  options: { title: "Options", language: "Language", controls: "Controls", accessibility: "Accessibility", defaults: "Restore default settings", languageInfo: "Choose the interface language.", controlsInfo: "Arrows: move. Shift plus arrows: look.", accessibilityInfo: "Announcements compatible with screen readers.", defaultsInfo: "Settings restored." },
  credits: { title: "Credits", description: "Zenit is developed by the Euconcegojogar team.", contact: "Contact: euconcego@gmail.com", back: "Press Escape to go back." },
  startup: { newGame: "New game started.", controls: "Use the arrow keys to move and C to open the menu." }, common: { choose: "Use the arrow keys to choose and Enter to confirm.", back: "Press Escape to go back." },
  gameplay: { map: "Map", level: "level", mainMenu: "Main menu", status: "Status", inventory: "Inventory", equipment: "Equipment", class: "Class", power: "Power", coordination: "Coordination", mind: "Mind", hp: "HP", stamina: "Stamina", mana: "Mana", gold: "Gold", empty: "Empty", box: "Box", range: "range", head: "Head", neck: "Neck", ring1: "Ring 1", ring2: "Ring 2", torso: "Torso", body: "Over the Body", waist: "Waist", legs: "Legs", feet: "Feet", melee: "Melee Weapon", ranged: "Ranged Weapon", shield: "Shield", direction: { CIMA: "up", BAIXO: "down", ESQUERDA: "left", DIREITA: "right" }, item: { "Vanguarda / Campeão": "Vanguard / Champion", "Caçador / Patrulheiro": "Hunter / Ranger", "Místico / Erudito": "Mystic / Scholar", "Espada Curta": "Short Sword", "Arco Curto": "Short Bow" }, messages: { boundary: "Map boundary reached.", doorAhead: " Door ahead. Press Enter to open.", boxAhead: " The box must be destroyed or avoided.", blocked: "Path blocked to", scanWall: "wall at", scanBox: "box at", scanDoor: "door at", scanNone: "no relevant obstacle or door in view", scanDone: "Cone scan complete", noWeapon: "No weapon is equipped in this instance.", attackWall: "Attack blocked by wall at", attackDoor: "The door blocks the attack. Press Enter to interact with it.", destroyed: "destroyed. You found", total: "Total", attackDone: "Attack performed with", noTarget: "No target in range.", nothing: "Nothing to interact with in this direction.", doorOpened: "Door opened. You advanced to", activeWeapon: "Active weapon", none: "none", looking: "You are looking", look: "Looking toward", menuHint: "Use the arrows, Enter to select, and Escape to close.", submenuStatus: "Status submenu.", submenuEquipment: "Equipment submenu.", inventoryEmpty: "Inventory is empty.", option: "Option" } }
 }
};
const KEY = "zenit.language";
export function getSavedLanguage() { try { const value = localStorage.getItem(KEY); return LANGUAGES.some(({ code }) => code === value) ? value : null; } catch { return null; } }
export function saveLanguage(value) { try { localStorage.setItem(KEY, value); } catch {} }
export function getText(language, path) { return path.split(".").reduce((value, key) => value && value[key], P[language] || P["pt-BR"]) || path; }
