export const LANGUAGES = [{ code: "pt-BR", label: "Português (Brasil)" }, { code: "en", label: "English" }];
const P = {
 "pt-BR": { language: { title: "Selecione o idioma", description: "Escolha o idioma da interface.", hint: "Use as setas para escolher e Enter para confirmar.", selected: "Idioma selecionado." }, main: { title: "Menu principal", continue: "Continuar jogo", newGame: "Novo jogo", options: "Opções", credits: "Créditos", noSave: "Nenhum jogo salvo disponível." }, options: { title: "Opções", language: "Idioma", controls: "Controles", accessibility: "Acessibilidade", defaults: "Restaurar configurações padrão", languageInfo: "Selecione o idioma da interface.", controlsInfo: "Setas: mover. Shift mais setas: olhar.", accessibilityInfo: "Anúncios compatíveis com leitores de tela.", defaultsInfo: "Configurações restauradas." }, credits: { title: "Créditos", description: "Zenit é desenvolvido pela equipe Euconcegojogar.", contact: "Contato: euconcego@gmail.com", back: "Pressione Escape para voltar." }, startup: { newGame: "Novo jogo iniciado.", controls: "Use as setas para mover e C para abrir o menu." }, common: { choose: "Use as setas para escolher e Enter para confirmar.", back: "Pressione Escape para voltar." } },
 en: { language: { title: "Select language", description: "Choose the interface language.", hint: "Use the arrow keys to choose and Enter to confirm.", selected: "Language selected." }, main: { title: "Main menu", continue: "Continue game", newGame: "New game", options: "Options", credits: "Credits", noSave: "No saved game is available." }, options: { title: "Options", language: "Language", controls: "Controls", accessibility: "Accessibility", defaults: "Restore default settings", languageInfo: "Choose the interface language.", controlsInfo: "Arrows: move. Shift plus arrows: look.", accessibilityInfo: "Announcements compatible with screen readers.", defaultsInfo: "Settings restored." }, credits: { title: "Credits", description: "Zenit is developed by the Euconcegojogar team.", contact: "Contact: euconcego@gmail.com", back: "Press Escape to go back." }, startup: { newGame: "New game started.", controls: "Use the arrow keys to move and C to open the menu." }, common: { choose: "Use the arrow keys to choose and Enter to confirm.", back: "Press Escape to go back." } }
};
const KEY = "zenit.language";
export function getSavedLanguage() { try { const value = localStorage.getItem(KEY); return LANGUAGES.some(({ code }) => code === value) ? value : null; } catch { return null; } }
export function saveLanguage(value) { try { localStorage.setItem(KEY, value); } catch {} }
export function getText(language, path) { return path.split(".").reduce((value, key) => value && value[key], P[language] || P["pt-BR"]) || path; }
